apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name:  batch-job-everyfifteen-minuts
spec:
  schedule: "0,15,30,45 * * * *"
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: periodic-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
          - name: main
            image: lukia/naych-jib2
